table_cond_formatting_rules:
  #scores_nanobert_table-l_RMSd:
  l_RMSd:
    correct:
      - lt: 0.92
    suspect:
      - gt: 0.92 
    unreliable:
      - gt: 3.10

table_cond_formatting_colours:
  - correct: "#5cb85c"
  - suspect: "#f0ad4e"
  - unreliable: "#d9534f"

custom_data:

  scores_nanobert_table:
    id: 'scores_nanobert_table'
    parent_id: scores_nanobert
    parent_name: 'nanobert scores'
    section_name: 'nanobert scores'
    description: 'nanobert scores'
    plot_type: 'table'
    pconfig:
      id: 'scores_nanobert_table'
      format: '{:,.3f}'

  scores_nanobert_plot:
    id: 'scores_nanobert_plot'
    file_format: "tsv"
    parent_id: scores_nanobert
    parent_name: 'nanobert scores'
    section_name: 'nanobert scores'
    description: 'nanobert scores'
    plot_type: 'scatter'
    pconfig:
      id: 'scores_nanobert_plot'
      format: '{:,.3f}'

  nanobert_legend:
    id: 'nanobert_legend'
    parent_id: legend
    parent_name: 'Legend'
    section_name: 'nanobert scores'
    description: 'Colour legend for the confidence of the l-RMSd score'
    plot_type: 'html'
    data: |
      <style type="text/css">
      table td#correct {padding:0 15px; background-color:#5cb85c;}
      table td#suspect {padding:0 15px; background-color:#f0ad4e;}
      table td#unreliable {padding:0 15px; background-color:#d9534f;}
      table td#range {padding:0 15px;}
      table th#range {padding:0 15px;}
      </style>
      <table>
        <tr>
          <th>Status</th>
          <th id="range">Range</th>
        </tr>
        <tr>
          <td id="correct">Correct</td>
          <td id="range"> l-RMSd < 0.92 </td>
        </tr>
        <tr>
          <td id="suspect">Suspect</td>
          <td id="range"> 0.92 < l-RMSd < 3.10 </td>
        </tr>
        <tr>
          <td id="unreliable" >Unreliable</td>
          <td id="range"> l-RMSd > 3.10 </td>
        </tr>
      </table>

  definition_legend:
    id: 'definition_legend'
    parent_id: legend
    parent_name: 'Legend'
    section_name: 'Definitions'
    plot_type: 'html'
    data: |
      <dl class="dl-horizontal">
          <dt>g-RMSD</dt><dd><samp>This is the global Root Mean Square Deviation. The compounds of interest are structurally aligned on Cα-atoms of the AlphaFold model; the g-RMSD is the RMSD calculated from this alignment (Hekkelman et al. 2023).</samp></dd>
          <dt>l-RMSD</dt><dd><samp>This is the local Root Mean Square Deviation. Starting from the closest homolog, all backbone atoms within 6 Å from the atoms of each compound that will be considered for ‘transplantation’ are selected and used for a local structural alignment to the AlphaFold model; the l-RMSD is the RMSD calculated from this alignment (Hekkelman et al. 2023). The l-RMSD is a proxy to assess the local environment validation (LEV) score. The LEV is defined as the all-atom RMSD of any ligand atom and all proteins’ atoms within 6.0 Å from the ligand, between the nanobert and experimental complexes.</samp></dd>
      </dl>


  reference_legend:
    id: 'reference_legend'
    parent_id: legend
    parent_name: 'Legend'
    section_name: 'References'
    description: 'List of publications'
    plot_type: 'html'
    data: |
      <ul>
        <li>Johannes Thorling Hadsund, Tadeusz Satława, Bartosz Janusz, Lu Shan, Li Zhou, Richard Röttger, Konrad Krawczyk, nanoBERT: a deep learning model for gene agnostic navigation of the nanobody mutational space, Bioinformatics Advances, Volume 4, Issue 1, 2024, vbae033, <a href="https://doi.org/10.1093/bioadv/vbae033">https://doi.org/10.1093/bioadv/vbae033</a></li>
      </ul>

sp:

  scores_nanobert_table:
    fn: 'nanobert_matrix_scores.tsv'

  scores_nanobert_plot:
    fn: 'nanobert_scores.tsv'

report_section_order:
  scores_nanobert_table:
    order: -1000
  legend:
    order: -1500
  nanobert_legend:
    order: -1490
  definition_legend:
    order: -1480
  reference_legend:
    order: -1470
