table_cond_formatting_rules:
  #scores_alphafill_table-l_RMSd:
  l_RMSd:
    correct:
      - lt: 0.92
    suspect:
      - gt: 0.92 
    unreliable:
      - gt: 3.10

table_cond_formatting_colours:
  - correct: "#5cb85c"
  - suspect: "#f0ad4e"
  - unreliable: "#d9534f"

custom_data:

  scores_alphafill_table:
    id: 'scores_alphafill_table'
    parent_id: scores_alphafill
    parent_name: 'AlphaFill scores'
    section_name: 'AlphaFill scores'
    description: 'AlphaFill scores'
    plot_type: 'table'
    pconfig:
      id: 'scores_alphafill_table'
      format: '{:,.3f}'

  alphafill_legend:
    id: 'alphafill_legend'
    parent_id: legend
    parent_name: 'Legend'
    section_name: 'AlphaFill scores'
    description: 'Colour legend for the confidence of the l-RMSd score'
    plot_type: 'html'
    data: |
            <style type="text/css">
            table td#correct {padding:0 15px; background-color:#5cb85c;}
            table td#suspect {padding:0 15px; background-color:#f0ad4e;}
            table td#unreliable {padding:0 15px; background-color:#d9534f;}
            table td#range {padding:0 15px;}
            table th#range {padding:0 15px;}
            </style>
            <table>
              <tr>
                <th>Status</th>
                <th id="range">Range</th>
              </tr>
              <tr>
                <td id="correct">Correct</td>
                <td id="range"> l-RMSd < 0.92 </td>
              </tr>
              <tr>
                <td id="suspect">Suspect</td>
                <td id="range"> 0.92 < l-RMSd < 3.10 </td>
              </tr>
              <tr>
                <td id="unreliable" >Unreliable</td>
                <td id="range"> l-RMSd > 3.10 </td>
              </tr>
            </table>

  reference_legend:
    id: 'reference_legend'
    parent_id: legend
    parent_name: 'Legend'
    section_name: 'References'
    description: 'List of publications'
    plot_type: 'html'
    data: |
            <ul>
              <li>Hekkelman, M.L., de Vries, I., Joosten, R.P. et al. AlphaFill: enriching AlphaFold models with ligands and cofactors. Nat Methods 20, 205–213 (2023). <a href="https://www.nature.com/articles/s41592-022-01685-y">https://doi.org/10.1038/s41592-022-01685-yi</a></li>
            </ul>

sp:

  scores_alphafill_table:
    fn: 'scores_alphafill.tsv'

report_section_order:
  scores_alphafill_table:
    order: -1000
  alphafill_legend:
    order: -500
  reference_legend:
    order: -400
