/*
Copyright Institut Curie 2024

This software is a computer program whose purpose is to
predict 3D structure of proteins.
You can use, modify and/ or redistribute the software under the terms
of license (see the LICENSE file for more details).
The software is distributed in the hope that it will be useful,
but "AS IS" WITHOUT ANY WARRANTY OF ANY KIND.
Users are therefore encouraged to test the software's suitability as regards
their requirements in conditions enabling the security of their systems and/or data.
The fact that you are presently reading this means that you have had knowledge
of the license and that you accept its terms.

*/

// This process launches AlphaFold:
//   - https://github.com/GBLille/MassiveFold
// The AlphaFold options are generated by the process alphaFoldOptions
process massiveFoldSearch {
  tag "${fastaFile}"
  label 'massiveFold'
  label 'highMem'
  label 'highCpu'
  publishDir path: { "${params.outDir}/massiveFoldSearch/${fastaFile}".replace('.fasta', '') }, mode: 'copy'
  containerOptions "--env AF_HHBLITS_N_CPU=${task.cpus} --env AF_JACKHMMER_N_CPU=${task.cpus} -B \$PWD:/tmp"

  input:
  path fastaFile
  path alphaFoldOptions
  path massiveFoldDatabase

  output:
  path("predictions", type: 'dir', emit: msas)
  path(fastaFile, emit: fastaFile)

  script:
  // massiveFold is alphaFold-like, therefore some variables contain alphaFold on purpose
  """
  alphafold_options=\$(cat ${alphaFoldOptions})
  launch_alphafold.sh --fasta_paths=${fastaFile} \${alphafold_options} --only_msas
  """
}

